config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'homes/achievement', to: 'homes#achievement'
  get 'homes/top'
  devise_for :users
  resources :tasks,only: [:index, :new, :create, :show, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    tasks_path
  end

  protected

   def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  # 達成した目標だけ表示する
  def achievement
    @tasks = Task.all.where(achievement: true)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to tasks_path
    else
      render :new
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def show
  end

  def index
    @tasks = Task.all.where(achievement: false)
  end

  private
    def task_params
      params.require(:task).permit(:deadline, :task, :comment, :achievement)
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/achievement.html.erb
<h1  class="text-center">達成済み目標</h1>
<%= link_to "目標の設定", new_task_path %>
<p  class="text-center">達成済みの目標一覧です</p>
<table class="table table-dark">
<tbody>
<!--達成した目標のみ表示-->
<% @tasks.each do |task| %>
<div class="card" style="width:300px;">
  <div class="card-body">
    <h4 class="card-title">目標<%= task.task %></h4>
    <p class="card-text">補足<%= task.comment %></p>
  </div>
</div>
<% end %>
</tbody>
</table>

app/views/homes/top.html.erb
<h1 class="text-center">目標達成</h1>
<p  class="text-center">目標を決めて達成したかどうか管理するアプリです。</br>
さっそく始めましょう</p>

<div class="row justify-content-center">
<%= link_to "ユーザー登録をする", new_user_registration_path, class:"btn btn-success"  %>
<%= link_to "ユーザーログインする", new_user_session_path, class:"btn btn-primary"  %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MokuhyoTassei</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="sticky-top"> <!--ヘッダーを画面上部へ固定-->
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark text-white"> <!--navバーの作成-->
        <!--アプリケーションのiconを表示(後日）-->
        <!--%= image_tag "", width: "5%" %>-->
        <!--アプリケーション名を表示-->
          <%= link_to "MOKUHYO TASSEI", root_path,class: "navbar-brand" %>
        <!--ハンバーガーメニューの作成-->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
      <!--ユーザーサインイン後のヘッダー-->
        <% if user_signed_in? %>
            <li class="nav-item active">
              <%= link_to "目標を投稿する", new_task_path, class: "nav-link" %>
            </li>
        <li class="nav-item active">
          <%= link_to "目標一覧", tasks_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>

        <% else %>
        <!--ユーザーログアウト後のヘッダー-->
        <li class="nav-item active">
         <%= link_to "ユーザーログイン", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "新規ユーザー登録", new_user_registration_path, class: "nav-link" %>
        </li>
        <% end %>
        </ul>
      </div>
　    </nav>
    </header>
    <%= yield %>

      <footer class="bg-dark text-white mt-5 pt-5 pb-4">
      <!--アプリの文字と作成者-->
      <div class="row justify-content-center">
      <p>MOKUHYO TASSEI</br>
      made by REIKOPI</p>
      </div>
    </footer>

  </body>
</html>

app/views/tasks/edit.html.erb
<h1 class="text-center">目標編集</h1>

<div class="text-center">
<%= form_with model: @task, url: task_path, method: :patch do |f| %>

<table class="table">
    <tbody>
        <tr><th class="table-active">締切</th>
        <th><%= f.date_field :deadline %></th></tr>

        <tr><th class="table-active">目標</th>
        <th><%= f.text_area :task %></th></tr>

        <tr><th class="table-active">補足</th>
        <th><%= f.text_area :comment %></th></tr>

        <tr><th class="table-active">目標達成有無</th>
        <th><%= f.radio_button :achievement, true %>
            <%= f.label :achievement, "達成" %>
            <%= f.radio_button :achievement, false %>
            <%= f.label :achievement, "未達成" %></th></tr>
    </tbody>
</table>


<%= f.submit '目標を編集する', class:"btn btn-primary" %>
<% end %>

<%= link_to "目標一覧", tasks_path %>
</div>

app/views/tasks/index.html.erb
<h1  class="text-center">目標一覧</h1>
<h1><%= link_to "達成済み目標の一覧はこちら", homes_achievement_path, class:"btn btn-primary" %></h1>
<%= link_to "目標の設定", new_task_path %>
<p  class="text-center">設定した目標の一覧です</p>

<% @tasks.each do |task| %>
<div class="card" style="width:300px;">
  <div class="card-body">
    <h4 class="card-title">目標:<%= task.task %></h4>
    <p class="card-text">補足:<%= task.comment %></p>
    <a>目標達成締切:<%= task.deadline %></a>
    <a><%= link_to "修正", edit_task_path(task.id) %></a>
  </div>
</div>
<% end %>

app/views/tasks/new.html.erb
<h1  class="text-center">目標投稿</h1>

<p>目標を投稿する</p>
<%= form_with model: @task do |f| %>
<p>締切<%= f.date_field :deadline %></p>
<p>目標<%= f.text_area :task %></p>
<p>補足<%= f.text_area :comment %></p>

<%= f.submit '目標を投稿する', class:"btn btn-primary" %>
<% end %>

<%= link_to "目標一覧", tasks_path %>